version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    resource_class: large  # Puede ser necesario para builds más grandes
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""

jobs:
  build:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7  # Versión de Docker a utilizar
          docker_layer_caching: true  # Habilita la caché de capas de Docker para builds más rápidas

      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential git wget curl python3-pip
            pip3 install --upgrade pip

      - run:
          name: Clone Batocera Repository
          command: |
            git clone --depth 1 https://github.com/adriarroyo08/batocera.linux
            cd batocera.linux
            git submodule update --init --recursive


      - run:
          name: Configurar Buildroot
          command: |
            cd batocera.linux/buildroot
            make menuconfig

      - run:
          name: Compilar Batocera
          command: |
            cd batocera.linux/buildroot
            make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
