name: Compile Batocera

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git wget

    - name: Build Batocera
      run: |
        git clone --depth 1 https://github.com/adriarroyo08/batocera.linux
        cd batocera.linux
        ./docker-run make

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: batocera-build
        path: batocera.linux/output/
