name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Actualizado a Node.js 20

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git wget

    - name: Build with Docker
      run: |
        cd ./
        ls
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: batocera-build
        path: /home/runner/work/batocera.linux/batocera.linux/output
